image: node:latest

stages:
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: deploy
  script:
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then cp -R ./* /home/ec2-user/discordbot_zbeub; fi
    - npm install 
  artifacts:
    paths:
      - node_modules/
