image: node:latest

    stages:
      - build
      - test

    cache:
      paths:
        - node_modules/

    install_dependencies:
      stage: build
      script:
        - rm -rf ./home/ec2-user/discordbot_zbeub
        - cp -r ./* /home/ec2-user 
        - npm install 
      artifacts:
        paths:
          - node_modules/

    testing_testing:
      stage: test
      script: npm test