image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - sudo rm -rf ./home/ec2-user/discordbot_zbeub
    - sudo cp -r ./* /home/ec2-user/discordbot_zbeub
    - sudo npm install 
  artifacts:
    paths:
      - node_modules/
