image: node:latest

stages:
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: deploy
  script:
    - sudo cp -R ./* /home/ec2-user/discordbot_zbeub
    - sudo cd node
    - echo "Installing node_modules dependencies"
    - sudo npm install
    - sudo cd ../
    - echo "Installing python dependencies"
    - sudo python/sh/install_dependencies.sh
  artifacts:
    paths:
      - node_modules/
