image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - sudo rm -rf ~/discordbot_zbeub
    - sudo mkdir ~/discordbot_zbeub
    - sudo cp -r ./* ~/discordbot_zbeub
    - sudo npm install 
  artifacts:
    paths:
      - node_modules/
