resources:
- name: repo
  type: git
  source:
    uri: https://gitlab.com/ant.hakim.stud/discord_bot.git
    branch: feature/drinks
    #private_key: ((private-repo-key))
- name: node-image
  type: registry-image
  source:
    repository: node
    tag: 13.10.1-stretch

jobs:
- name: test
  public: true
  plan:
  - get: node-image
  - get: repo
    trigger: true
  - task: install
    image: node-image
    config:
      inputs:
      - name: repo
      outputs:
      - name: dependencies
        path: repo/node_modules
      platform: linux
      run:
        path: npm
        args: ["install"]
        dir: repo
  - task: test
    image: node-image
    config:
      inputs:
      - name: repo
      - name: dependencies
        path: repo/node_modules
      platform: linux
      run:
        path: npm
        args: ["run", "test"]
        dir: repo